### ISSUE TITLE
[Example] Step 1 - Given the existing data, query the structured list of indications (Radiology)

### ISSUE THREAD

**Issue by NISN-SMALS** [hl7-be/pss#25]
**Custom endpoint**

GET - https://www.ehealth.fgov.be/standards/fhir/pss/OperationDefinition/getIndications?
age=37&gender=female&snomed_code=763597000&freetext_indication=Ataxia&examination=114055

**OperationDefinition specifications**

```yaml
{
  "resourceType": "OperationDefinition",
  "id": "indications",
  "url": "https://www.ehealth.fgov.be/standards/fhir/pss/OperationDefinition/getIndications",
  "version": "1.0.0",
  "name": "GetIndications",
  "status": "active",
  "kind": "operation",
  "code": "getIndications",
  "system": true,
  "type": false,
  "instance": false,
  "parameter": [
    {
      "name": "age",
      "use": "in",
      "min": 1,
      "max": "1",
      "type": "integer",
      "documentation": "Age of the patient"
    },
    {
      "name": "gender",
      "use": "in",
      "min": 1,
      "max": "1",
      "type": "code",
      "documentation": "Gender of the patient, possible values are: male, female, unknown"
    },
    {
      "name": "snomed_code",
      "use": "in",
      "min": 1,
      "max": "*",
      "type": "CodeableConcept",
      "documentation": "The SNOMED code(s) for the condition(s).",
      "binding": {
        "strength": "required",
        "valueSet": "https://www.ehealth.fgov.be/standards/fhir/pss/ValueSet/be-pss-indications"
      }
    },
    {
      "name": "freetext_indication",
      "use": "in",
      "min": 0,
      "max": "*",
      "type": "string",
      "documentation": "The free text indication(s) of the patient's condition(s)."
    },
    {
      "name": "examination",
      "use": "in",
      "min": 0,
      "max": "1",
      "type": "integer",
      "documentation": "Optional examination code"
    },
    {
      "name": "return",
      "use": "out",
      "min": 1,
      "max": "1",
      "type": "Questionnaire"
    }
  ]
}
```
