### ISSUE TITLE
[Example] Step 2 - Response with list of structured indications (Radiology)

### ISSUE THREAD

**Issue by NISN-SMALS** [hl7-be/pss#26]
**Response**: this response is based on the parameters provided in step 1

```yaml
{
  "resourceType": "Questionnaire",
  "id": "indications-response",
  "name": "IndicationsResponse",
  "title": "List of Indications",
  "status": "active",
  "description": "Questionnaire containing a list of indications for the patient",
  "item": [
    {
      "linkId": "1",
      "text": "Indications",
      "type": "choice",
      "required": true,
      "repeats": true,
      "answerOption": [
        {
          "valueCoding": {
            "system": "http://snomed.info/sct",
            "code": "763597000" //Hereditary ataxia
          }
        },
        {
          "valueCoding": {
            "system": "http://snomed.info/sct",
            "code": "230233000" //Progressive cerebellar ataxia
          }
        }
      ]
    }
  ]
}
```
