### ISSUE TITLE
[Example] Step 3 - Send indications to receive the support options (Radiology)

### ISSUE THREAD

**Issue by NISN-SMALS** [hl7-be/pss#27]
**Request:** POST /$RadioGuidanceRequest (+ QuestionnaireResponse in payload)

**OperationDefinition specifications**

```yaml
{
  "resourceType": "OperationDefinition",
  "id": "radioguidance-request",
  "url": "https://www.ehealth.fgov.be/standards/fhir/pss/OperationDefinition/radioguidance-request",
  "version": "1.0",
  "name": "RadioGuidanceRequest",
  "status": "active",
  "kind": "operation",
  "code": "radioGuidanceRequest",
  "system": true,
  "instance": false,
  "type": false,
  "parameter": [
    {
      "name": "response",
      "type": "QuestionnaireResponse",
      "use": "in",
      "min": 1,
      "max": "1",
      "documentation": "The indications selected by EPD"
    },
    {
      "name": "return",
      "type": "Bundle",
      "use": "out",
      "min": 1,
      "max": "1",
      "documentation": "The operation returns a Bundle containing a GuidanceResponse and a Parameters resource."
    }
  ]
}
```
**Post body:** In this example indication "Hereditary ataxia" is selected out of the list of structured indications that we received in step 2.

```yaml
{
  "resourceType": "QuestionnaireResponse",
  "status": "completed",
  "item": [
    {
      "linkId": "1",
      "text": "Indication selected by EPD",
      "answer": [
        {
          "valueCoding": {
            "system": "http://snomed.info/sct",
            "code": "763597000" //Hereditary ataxia
          }
        }
      ]
    }
  ]
}
```
