### ISSUE TITLE
[Example] Step 1 - Send indication (Antimicrobial)

### ISSUE THREAD

**Issue by NISN-SMALS** [hl7-be/pss#28]
**Custom endpoint**

GET - http://www.ehealth.fgov.be/standards/fhir/pss/OperationDefinition/requiredDataForAntimicro-request?indication.system=http://snomed.info/sct&indication.code=921000172108&indication.display=Acute%20keelpijn

**OperationDefinition specifications**

```yaml
{
  "resourceType": "OperationDefinition",
  "id": "requireddataforantimicro-request",
  "url": "https://www.ehealth.fgov.be/standards/fhir/pss/OperationDefinition/requireddataforantimicro-request",
  "version": "1.0",
  "name": "RequiredDataForAntimicro",
  "status": "active",
  "kind": "operation",
  "code": "requiredDataForAntimicro",
  "system": true,
  "type": false,
  "instance": false,
  "parameter": [
    {
      "name": "indication",
      "use": "in",
      "min": 1,
      "max": "1",
      "documentation": "The indication selected by EPD",
      "type": "Coding"
    },
    {
      "name": "return",
      "use": "out",
      "min": 1,
      "max": "1",
      "type": "Questionnaire"
    }
  ]
}
```
