### ISSUE TITLE
[Example] Step 2 - Reply with list of required data (Antimicrobial)

### ISSUE THREAD

**Issue by NISN-SMALS** [hl7-be/pss#29]
**Response**: this response is based on the indication provided in step 1

```yaml
{
  "resourceType": "Questionnaire",
  "id": "requireddataforantimicro-response",
  "title": "Required Data for Antimicro",
  "status": "active",
  "subjectType": [
    "Patient"
  ],
  "item": [
    {
      "linkId": "questionnaire",
      "type": "group",
      "item": [
        {
          "linkId": "sp_alertSignals",
          "type": "boolean"
        },
        {
          "linkId": "sp_isSeverelyIll",
          "type": "boolean"
        },
        {
          "linkId": "sp_riskPatientGroup",
          "type": "group",
          "item": [
            {
              "linkId": "sp_riskPatient",
              "type": "boolean"
            },
            {
              "linkId": "sp_riskPatient_patientVariables",
              "type": "group",
              "item": [
                {
                  "linkId": "pv_compromisedImmuneSystem_proposals",
                  "type": "group",
                  "item": [
                    {
                      "linkId": "pv_compromisedImmuneSystem",
                      "type": "choice",
                      "repeats": true,
                      "answerOption": [
                        {
                          "valueCoding": {
                            "system": "http://www.who.int/classifications/icpc2",
                            "code": "B90"
                          }
                        },
                        {
                          "valueCoding": {
                            "system": "http://www.who.int/classifications/icd10",
                            "code": "D70"
                          }
                        },
                        {
                          "valueCoding": {
                            "system": "http://snomed.info/sct",
                            "code": "234532001"
                          }
                        }
                      ]
                    },
                    {
                      "linkId": "pv_compromisedImmuneSystem_override",
                      "type": "boolean"
                    }
                  ]
                },
                {
                  "linkId": "pv_oncologyPatient_proposals",
                  "type": "group",
                  "item": [
                    {
                      "linkId": "pv_oncologyPatient",
                      "type": "choice",
                      "repeats": true,
                      "answerOption": [
                        {
                          "valueCoding": {
                            "system": "http://www.who.int/classifications/icpc2",
                            "code": "R84"
                          }
                        },
                        {
                          "valueCoding": {
                            "system": "http://www.who.int/classifications/icd10",
                            "code": "C00-C97"
                          }
                        },
                        {
                          "valueCoding": {
                            "system": "http://snomed.info/sct",
                            "code": "763597000"
                          }
                        }
                      ]
                    },
                    {
                      "linkId": "pv_oncologyPatient_override",
                      "type": "boolean"
                    }
                  ]
                },
                {
                  "linkId": "pv_historyAcuteJointRheumatism_proposals",
                  "type": "group",
                  "item": [
                    {
                      "linkId": "pv_historyAcuteJointRheumatism",
                      "type": "choice",
                      "repeats": true,
                      "answerOption": [
                        {
                          "valueCoding": {
                            "system": "http://www.who.int/classifications/icd10",
                            "code": "M02.8"
                          }
                        },
                        {
                          "valueCoding": {
                            "system": "http://snomed.info/sct",
                            "code": "404684003"
                          }
                        }
                      ]
                    },
                    {
                      "linkId": "pv_historyAcuteJointRheumatism_override",
                      "type": "boolean"
                    }
                  ]
                },
                {
                  "linkId": "pv_recentProthesticSurgery_proposals",
                  "type": "group",
                  "item": [
                    {
                      "linkId": "pv_recentProthesticSurgery",
                      "type": "choice",
                      "repeats": true,
                      "answerOption": [
                        {
                          "valueCoding": {
                            "system": "http://www.who.int/classifications/icpc2",
                            "code": "A89"
                          }
                        },
                        {
                          "valueCoding": {
                            "system": "http://www.who.int/classifications/icd10",
                            "code": "M96.6"
                          }
                        },
                        {
                          "valueCoding": {
                            "system": "http://snomed.info/sct",
                            "code": "67270000"
                          }
                        }
                      ]
                    },
                    {
                      "linkId": "pv_recentProthesticSurgery_override",
                      "type": "boolean"
                    }
                  ]
                },
                {
                  "linkId": "pv_heartValveDisease_proposals",
                  "type": "group",
                  "item": [
                    {
                      "linkId": "pv_heartValveDisease",
                      "type": "choice",
                      "repeats": true,
                      "answerOption": [
                        {
                          "valueCoding": {
                            "system": "http://www.who.int/classifications/icpc2",
                            "code": "K83"
                          }
                        },
                        {
                          "valueCoding": {
                            "system": "http://www.who.int/classifications/icd10",
                            "code": "I34"
                          }
                        },
                        {
                          "valueCoding": {
                            "system": "http://snomed.info/sct",
                            "code": "44241007"
                          }
                        }
                      ]
                    },
                    {
                      "linkId": "pv_heartValveDisease_override",
                      "type": "boolean"
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "linkId": "sp_nonIgEMediatedPeniAllergy",
          "type": "boolean"
        },
        {
          "linkId": "sp_igEMediatedPeniAllergy",
          "type": "boolean"
        }
      ]
    }
  ]
}
```

**Remarks:**
- Only a few ICPC-2, ICD-10 and SNOMED codes are listed in the example, a full list of codes will be sent linked to the indication
- How will we handle the translations? Possible solutions can be found here https://build.fhir.org/languages.html to be discussed
