### ISSUE TITLE
[Example] Step 3 - Send parameters to receive support options (Antimicrobial)

### ISSUE THREAD

**Issue by NISN-SMALS** [hl7-be/pss#30]
**Request:** POST /$AntimicroGuidanceRequest (+ QuestionnaireResponse in payload)

**OperationDefinition specifications**

```yaml
{
  "resourceType": "OperationDefinition",
  "id": "antimicroguidance-request",
  "url": "https://www.ehealth.fgov.be/standards/fhir/pss/OperationDefinition/AntimicroGuidanceRequest",
  "version": "1.0",
  "name": "AntimicroGuidance",
  "status": "active",
  "kind": "operation",
  "description": "Request for antimicrobial guidance based on patient condition and support parameters",
  "code": "antimicroGuidanceRequest",
  "system": true,
  "type": false,
  "instance": false,
  "parameter": [
    {
      "name": "questionnaireResponse",
      "use": "in",
      "min": 1,
      "max": "1",
      "documentation": "The response to the support parameters and patient variables questionnaire",
      "type": "QuestionnaireResponse"
    },
    {
      "name": "return",
      "use": "out",
      "min": 1,
      "max": "1",
      "type": "Bundle",
      "documentation": "The operation returns a Bundle containing a GuidanceResponse and a Parameters resource."
    }
  ]
}
```
**Post body:** In this example the following information is provided based on step 2:
- SupportParameter "sp_isSeverelyIll" is manually checked by the prescriber
- PatientVariable "pv_compromisedImmuneSystem_override" is manually checked by the prescriber
- PatientVariable "pv_oncologyPatient" is automatically filled with the snomed code "763597000" that was present in the EPD/UHMEP.

```yaml
{
  "resourceType": "QuestionnaireResponse",
  "status": "completed",
  "item": [
    {
      "linkId": "questionnaire",
      "item": [
        {
          "linkId": "indication",
          "text": "Indication",
          "answer": [
            {
              "valueCoding": {
                "system": "http://snomed.info/sct",
                "code": "921000172108" //Acute keelpijn
              }
            }
          ]
        },
        {
          "linkId": "sp_alertSignals",
          "answer": [
            {
              "valueBoolean": false
            }
          ]
        },
        {
          "linkId": "sp_isSeverelyIll",
          "answer": [
            {
              "valueBoolean": true
            }
          ]
        },
        {
          "linkId": "sp_riskPatientGroup",
          "item": [
            {
              "linkId": "sp_riskPatient",
              "answer": [
                {
                  "valueBoolean": false
                }
              ]
            },
            {
              "linkId": "sp_riskPatient_patientVariables",
              "item": [
                {
                  "linkId": "pv_compromisedImmuneSystem_proposals",
                  "item": [
                    {
                      "linkId": "pv_compromisedImmuneSystem_override",
                      "answer": [
                        {
                          "valueBoolean": true
                        }
                      ]
                    }
                  ]
                },
                {
                  "linkId": "pv_oncologyPatient_proposals",
                  "item": [
                    {
                      "linkId": "pv_oncologyPatient",
                      "answer": [
                        {
                          "valueCoding": {
                            "system": "http://snomed.info/sct",
                            "code": "763597000"
                          }
                        }
                      ]
                    },
                    {
                      "linkId": "pv_oncologyPatient_override",
                      "answer": [
                        {
                          "valueBoolean": false
                        }
                      ]
                    }
                  ]
                },
                {
                  "linkId": "pv_historyAcuteJointRheumatism_proposals",
                  "item": [
                    {
                      "linkId": "pv_historyAcuteJointRheumatism_override",
                      "answer": [
                        {
                          "valueBoolean": false
                        }
                      ]
                    }
                  ]
                },
                {
                  "linkId": "pv_recentProthesticSurgery_proposals",
                  "item": [
                    {
                      "linkId": "pv_recentProthesticSurgery_override",
                      "answer": [
                        {
                          "valueBoolean": false
                        }
                      ]
                    }
                  ]
                },
                {
                  "linkId": "pv_heartValveDisease_proposals",
                  "item": [
                    {
                      "linkId": "pv_heartValveDisease_override",
                      "answer": [
                        {
                          "valueBoolean": false
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "linkId": "sp_nonIgEMediatedPeniAllergy",
          "answer": [
            {
              "valueBoolean": false
            }
          ]
        },
        {
          "linkId": "sp_igEMediatedPeniAllergy",
          "answer": [
            {
              "valueBoolean": false
            }
          ]
        }
      ]
    }
  ]
}
```
